//
// Created by hackerl on 11/11/18.
//

#ifndef SHADOWSOCKSR_CPP_NODESERVICE_H
#define SHADOWSOCKSR_CPP_NODESERVICE_H

enum NodeServiceRegister : unsigned int
{
    INIT_REMOTE_SOCKET = 0,
    REQUEST_SOCKET_CONNECT,
    REQUEST_CLOSE_PIPE
};

#endif //SHADOWSOCKSR_CPP_NODESERVICE_H
